<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414082032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_lote VARCHAR(100) NOT NULL, fecha_fabricacion DATE NOT NULL, fecha_caducidad DATE NOT NULL, cantidad INT NOT NULL, producto_id INT NOT NULL, proveedor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65B4329F7645698E ON lote (producto_id)');
        $this->addSql('CREATE INDEX IDX_65B4329FCB305D73 ON lote (proveedor_id)');
        $this->addSql('CREATE TABLE movimiento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(50) NOT NULL, cantidad INT NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, descripcion TEXT DEFAULT NULL, lote_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8FF107AB172197C ON movimiento (lote_id)');
        $this->addSql('CREATE TABLE producto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, codigo VARCHAR(100) NOT NULL, categoria VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE proveedor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, contacto VARCHAR(255) DEFAULT NULL, pais VARCHAR(100) NOT NULL, email VARCHAR(180) DEFAULT NULL, telefono VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE lote ADD CONSTRAINT FK_65B4329F7645698E FOREIGN KEY (producto_id) REFERENCES producto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lote ADD CONSTRAINT FK_65B4329FCB305D73 FOREIGN KEY (proveedor_id) REFERENCES proveedor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107AB172197C FOREIGN KEY (lote_id) REFERENCES lote (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lote DROP CONSTRAINT FK_65B4329F7645698E');
        $this->addSql('ALTER TABLE lote DROP CONSTRAINT FK_65B4329FCB305D73');
        $this->addSql('ALTER TABLE movimiento DROP CONSTRAINT FK_C8FF107AB172197C');
        $this->addSql('DROP TABLE lote');
        $this->addSql('DROP TABLE movimiento');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE proveedor');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
